// Generated by Bisonc++ V4.13.01 on Thu, 02 Mar 2017 10:17:34 +0100

#ifndef Parser_h_included
#define Parser_h_included

// $insert baseclass
#include "parserbase.h"
// $insert scanner.h
#include "../scanner/scanner.h"

enum AngleMode
{
	DEGREES,
	RADIANS,
	GRAD
};

#undef Parser
class Parser: public ParserBase
{
    // $insert scannerobject
    Scanner d_scanner;
    
    AngleMode d_angleMode = RADIANS;
    
    public:
        int parse();

    private:
        void error(char const *msg);    // called on (syntax) errors
        int lex();                      // returns the next token from the
                                        // lexical scanner. 
        void print();                   // use, e.g., d_token, d_loc

    // support functions for parse():
        void executeAction(int ruleNr);
        void errorRecovery();
        int lookup(bool recovery);
        void nextToken();
        void print__();
        void exceptionHandler__(std::exception const &exc);
	
	// arithmetic functions:
		double angleTransform();
		
		double constant();
		
		void display(double &value);
        void done();
        void prompt();
		double exp(double &value);
		double ln(double &value);
		double sin(double &value);
		double asin(double &value);
		double sqrt(double &value);
		double abs(double &value);
		
		void deg();		
		void grad();
		void rad();
		
		double const pi = 3.14159;
		double const e = 2.71828;
		double constant();
};


#endif
